name: Run Python

on:
  workflow_dispatch:
  push:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4

      - name: Python 설치
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 라이브러리 설치
        run: pip install requests openai beautifulsoup4

      - name: 파이썬 실행
        run: python 0416navertime.py
