name: Run Python

on:
  workflow_dispatch:
  push:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests openai

      - name: Run script
        run: python 0416navertime.py
